image: python:latest

services:
  - postgres:latest

variables:
  SECRET_KEY: bg9kU6ckKXTLQeZxtovc
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  NAME: postgres

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt
  - ls
  - cp docker/config.py kees/config.py

test:
  script:
  - python manage.py test
