apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kees.fullname" . }}
  labels:
    {{- include "kees.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kees.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kees.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.dbHost }}
            - name: DB_USER
              value: {{ .Values.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.dbPassword }}
            - name: DB_NAME
              value: {{ .Values.dbName }}
            - name: SECRET_KEY
              value: {{ .Values.secretKey }}
            - name: ALLOWED_HOST
              value: {{ .Values.allowedHost }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
