{{- with set . "component" "postgres" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kees.fullname" . }}
  labels:
    {{- include "kees.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kees.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kees.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.postgresImage }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresDb }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: postgres
          readinessProbe:
            tcpSocket:
              port: postgres
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pvc
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistence.existingClaim }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kees.fullname" . }}
  labels:
    {{- include "kees.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "kees.selectorLabels" . | nindent 4 }}
{{- end }}