{{ with set . "component" "postgres" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {{ include "kees.common.metadata" . | nindent 2 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "kees.common.metadata-labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "kees.common.metadata-labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:11
          imagePullPolicy: {{.Values.imagePullPolicy}}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
              subPath: postgres
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pv
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: {{ include "kees.common.metadata" . | nindent 2 }}
spec:
  selector: {{ include "kees.common.metadata-labels" . | nindent 4 }}
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
{{ end }}