apiVersion: v1
kind: Service
metadata:
  name: {{ include "kees.fullname" . }}
  labels:
    {{- include "kees.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kees.selectorLabels" . | nindent 4 }}
