---
kees_version: "latest"
kees_path: "/opt/kees"
kees_ssl_enabled: false
kees_ssl_certificate: ""
kees_ssl_certificate_key: ""
kees_ssl_dhparam: ""
kees_ssl_ocsp_certificates: ""
kees_secret_key: "changetosomethingsecret"
kees_debug: false
kees_host: "kees.vagrant"
kees_db_user: "kees"
kees_db_password: "changetosomethingsecret"
kees_db_name: "kees"
kees_email_host: ""
kees_email_port: ""
kees_email_user: ""
kees_email_password: ""
kees_email_use_tls: false
kees_email_use_ssl: false
kees_email_from: ""
